# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.PositiveIntegerField(verbose_name='ID do Repositório')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('url', models.URLField(verbose_name='URL do Repositório')),
                ('username', models.CharField(max_length=255, verbose_name='Usuário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
