# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171013_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Linguagem'),
        ),
    ]
