# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import githubstars.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171014_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='tags',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[githubstars.core.models.validator_tags], verbose_name='Tags'),
        ),
    ]
